name: ghana_meals
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
          - asset: assets/font/Raleway-Regular.ttf
          - asset: assets/font/Raleway-Bold.ttf
            weight: 700
          - asset: assets/font/Raleway-Black.ttf
            weight: 900
    - family: RobotoCondensed
      fonts:
          - asset: assets/font/RobotoCondensed-Regular.ttf
          - asset: assets/font/RobotoCondensed-Bold.ttf
            weight: 700
          - asset: assets/font/RobotoCondensed-Italic.ttf
            style: italic
          - asset: assets/font/RobotoCondensed-Light.ttf
            weight: 300
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
